# https://www.home-assistant.io/integrations/default_config/
default_config:

# Added to allow get_url to work.
homeassistant:
  external_url: "https://localhost:8123"
  internal_url: "https://localhost:8123"

# Enable SSL, needed to auto reply to Miele Auth without error.
# Setup Script will create the certificates.
http:
  ssl_certificate: ./ssl/fullchain.pem
  ssl_key: ./ssl/privkey.pem

# Enable to initiate debugging in Home Assistant Runtime
debugpy:
  start: false
  wait: false

# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    custom_components.miele: debug
