# Example services.yaml entry

action:
  description: Runs action of Miele device
  fields:
    entity_id:
      description: Name(s) of the entities to set (optional, either set this or device_id)
      example: "miele.washing_machine"
      selector:
        entity:
          integration: miele
          domain: miele
    device_id:
      description: fab number of device to set (optional, either set this or entity_id)
      example: "000123456789"
      selector:
        text:
    body:
      description: The command to send
      example: "{\"powerOff\": true}"
      required: true
      selector:
        text:
          multiline: true

start_program:
  description: Starts a program on a Miele device
  fields:
    entity_id:
      description: Name(s) of the entities to set (optional, either set this or device_id)
      example: "miele.washing_machine"
      selector:
        entity:
          integration: miele
          domain: miele
    device_id:
      description: Fabrication number of device to set (optional, either set this or entity_id)
      example: "000123456789"
      selector:
        text:
    program_id:
      description: The program id to start
      example: 1
      required: true
      selector:
        number:

stop_program:
  description: Stops program on a Miele device
  fields:
    entity_id:
      description: Name(s) of the entities to set (optional, either set this or device_id)
      example: "miele.washing_machine"
      selector:
        entity:
          integration: miele
          domain: miele
    device_id:
      description: fab number of device to set (optional, either set this or entity_id)
      example: "000123456789"
      selector:
        text: