#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ ${BUILD_TYPE} == "run" ]; then
    # Start Home Assistant
    hass -c . --debug
else
    echo "Docker Mode: Build Type is not 'run', can't start hass. Build Type is ${BUILD_TYPE}."
fi

