#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

sudo apt -y update
sudo apt -y dist-upgrade
sudo apt -y install ffmpeg

pip install --upgrade pip

if [ ! -f ./configuration.yaml ]; then
  cp ./configuration-template.yaml ./configuration.yaml
fi

if [ ${BUILD_TYPE} == "dev" ]; then
    python3 -m pip install --requirement requirements_dev.txt
fi

if [ ${BUILD_TYPE} == "run" ]; then
    python3 -m pip install --requirement requirements.txt
fi
