#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ ! -f ./ssl/fullchain.pem ]; then
  mkdir ./ssl
  openssl req -sha256 -addext "subjectAltName = IP:127.0.0.1" -newkey rsa:4096 -nodes \
      -keyout ./ssl/privkey.pem -x509 -days 730 -out ./ssl/fullchain.pem \
      -subj "/C=GB/ST=None/L=None/O=None/OU=IT Department/CN=localhost"

  chown vscode:vscode ./ssl/fullchain.pem ./ssl/privkey.pem
  chmod 600 ./ssl/fullchain.pem ./ssl/privkey.pem
fi

sudo apt -y update
sudo apt -y dist-upgrade
sudo apt -y install ffmpeg

pip install --upgrade pip

if [ ! -f ./configuration.yaml ]; then
  cp ./configuration-template.yaml ./configuration.yaml
fi

if [ ${BUILD_TYPE} == "dev" ]; then
    python3 -m pip install --requirement requirements_dev.txt
fi

if [ ${BUILD_TYPE} == "run" ]; then
    python3 -m pip install --requirement requirements_hass.txt
fi
